version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # node_modules をホストと分離
    environment:
      - NODE_ENV=development
    command: npm run dev
